name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    uses: mafhper/release-core/.github/workflows/release.yml@v1.1.1
    with:
      matrix: |-
        [
          { "os": "macos-latest", "args": "--bundles app" },
          { "os": "ubuntu-latest", "args": "" },
          { "os": "windows-latest", "args": "" }
        ]